---
title: Daniele Ciulli
baseURL: "/"
params:
  description: Sito Web di Daniele CIulli
  layout_style: overflow
  palette: orange
  header:
    type: header
    template: header
    title: Daniele Ciulli
    tagline: Il Mio Sito Web
    profile_img: "/images/logo.png"
    background: dark
    has_nav: true
    nav_links:
    - type: action
      template: action
      label: Home
      url: "/"
      style: link
    - type: action
      template: action
      label: Fotografia
      url: "/blog/"
      style: link
    - type: action
      template: action
      label: Curriculum
      url: "/thank-you/"
      style: link
    - type: action
      template: action
      label: Su Di Me
      url: "/about/"
      style: link
    - type: action
      template: action
      label: Contatti
      url: "/contact/"
      style: link
    has_social: true
    social_links:
    - type: action
      template: action
      label: Twitter
      url: https://twitter.com/
      style: icon
      icon_class: fa-twitter
      new_window: true
    - type: action
      template: action
      label: Instagram
      url: https://www.instagram.com/
      style: icon
      icon_class: fa-instagram
      new_window: true
    - type: action
      template: action
      label: GitHub
      url: https://github.com/
      style: icon
      icon_class: fa-github
      new_window: true
    - type: action
      template: action
      label: LinkedIn
      url: https://www.linkedin.com/
      style: icon
      icon_class: fa-linkedin
      new_window: true
    - type: action
      template: action
      label: DEV
      url: https://dev.to/
      style: icon
      icon_class: fa-dev
      new_window: true
  footer:
    type: footer
    template: footer
    content: Vuoi un Sito come questo? Contattami!
    links: []
taxonomies:
  stub: stub
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
